apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/enterprise-contract/ec-cli?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "unified-build-release"
    pipelinesascode.tekton.dev/pipeline: ".tekton/cli-build.yaml"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: ec-release
    appstudio.openshift.io/component: ec-cli-with-bundle
    pipelines.appstudio.openshift.io/type: build
  name: ec-on-push
  namespace: lucarval-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/lucarval-tenant/ec-release/ec-cli-with-bundle:{{revision}}
    - name: image-expires-after
      value: ''
    - name: dockerfile
      value: Dockerfile.dist
    - name: path-context
      value: .
    - name: prefetch-input
      value: '[{"type": "gomod"}, {"type": "gomod", "path": "tools/kubectl"}, {"type": "rpm"}]'
    - name: build-source-image
      value: 'true'
    - name: build-args-file
      value: ''
    - name: hermetic
      value: 'true'
  pipelineRef:
    name: cli-build
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
