apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/lcarva/ec-cli?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
    pipelinesascode.tekton.dev/pipeline: ".tekton/task-build.yaml"
  labels:
    appstudio.openshift.io/application: ec
    appstudio.openshift.io/component: task
    pipelines.appstudio.openshift.io/type: build
  name: task-on-push
  namespace: lucarval-tenant
spec:
  # Note that some params here are not used since the build-container
  # task is tkn-bundle rather than buildah
  params:
    - name: dockerfile
      value: Dockerfile
    - name: git-url
      value: '{{source_url}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/lucarval-tenant/task:{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: '{{revision}}'
  pipelineRef:
    name: task-build
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
